apiVersion: v1
kind: Pod
metadata:
  name: conversao-temperatura
  labels:
    name: conversao-temperatura
spec:
  containers:
  - name: conversao-temperatura
    image: chmulato/conversao-temperatura:v2
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
